방 입장 관련 로직 구현
august-thirty-first/frontend pull request #76
Opened 2023-08-17 07:37 UTC by kimchijinju

## 관련 이슈
- #36 

## 요약
방 입장과 관련하여 검증받고 접속하는 로직을 작성했습니다.

<br><br>

## 작업내용
1. 방 리스트의 버튼을 누르면 비밀번호를 입력하는 창이 나오고, 입장 버튼을 누르면 api로 요청을 보내 비밀번호 검증과 채팅창 입장을 하도록 구현했습니다.
2. chat url에 접속했다면 해당 채팅방에 참가할 권한이 있는지 검증하는 로직을 추가했습니다.
3. chat url에서 query string로처리하던 room id를 parameter로 변경했습니다.
 
<br><br>

## 참고사항
구현이 오래걸려 죄송합니다. 😢
<br><br>

2023-08-17 08:47 UTC, flowjiyun requested changes
조건에 오류가 있는 것 같아서 해당 부분만 고치면 될거 같습니다

2023-08-17 08:47 UTC, flowjiyun commented on next/src/app/(home)/(communication)/channel/_room/roomBuilder.tsx
> +    if (statusCodeRef?.current === 200 || statusCodeRef?.current === 200) {
조건이 똑같은거 같아서 뭔가 수정이 필요해보입니다!

2023-08-17 10:36 UTC, kimchijinju commented on next/src/app/(home)/(communication)/channel/_room/roomBuilder.tsx
> +    if (statusCodeRef?.current === 200 || statusCodeRef?.current === 200) {
수정했습니다 감사합니다!

2023-08-18 01:05 UTC, flowjiyun approved these changes
수정된거 확인하였습니다

2023-08-18 01:22 UTC, merged